# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.show_config()


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels-jc1cl\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
np.size(z)

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info()


 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x0000019743D235C0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [11]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [7]:
x=np.random.random((3,3,3))
x

array([[[0.26553425, 0.7604276 , 0.93319904],
        [0.97954511, 0.98293663, 0.3146182 ],
        [0.20421495, 0.46828128, 0.90158973]],

       [[0.89253679, 0.06793755, 0.1489466 ],
        [0.6813617 , 0.72123474, 0.4080846 ],
        [0.92897766, 0.94880473, 0.56950048]],

       [[0.01072999, 0.83002915, 0.48874554],
        [0.49556845, 0.8390509 , 0.85345398],
        [0.8452008 , 0.17557237, 0.26935959]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
z=np.random.random((10,10))
print(z)
print(np.max(z))
print(np.min(z))

[[0.95144509 0.18284758 0.78309195 0.77359758 0.14393189 0.93532488
  0.3885654  0.72688977 0.69594583 0.02531924]
 [0.50878825 0.14132656 0.51529646 0.83574323 0.04360473 0.39709858
  0.78650097 0.25677423 0.32046408 0.82500256]
 [0.00627771 0.15017467 0.29184702 0.32022319 0.07372544 0.41470447
  0.24214649 0.37300417 0.94648326 0.93015956]
 [0.52292679 0.28728447 0.927534   0.43855536 0.52246276 0.3104713
  0.32490762 0.03794451 0.38320959 0.74588324]
 [0.92372731 0.64688648 0.64394644 0.31108147 0.41265565 0.00913976
  0.28102003 0.97011654 0.94129027 0.75512683]
 [0.79752441 0.45504287 0.53103259 0.79397415 0.19293068 0.96504488
  0.25820571 0.24808996 0.01711678 0.38162696]
 [0.73224361 0.53825644 0.43479964 0.48560154 0.55217059 0.80732818
  0.23622981 0.5847792  0.23441469 0.44386014]
 [0.22641771 0.47594811 0.97581842 0.57358393 0.67231605 0.00773418
  0.2362978  0.18569835 0.98396271 0.83275046]
 [0.49045527 0.06709592 0.92656853 0.01598567 0.64205602 0.4221327
  0.25071443 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
x=np.random.random(30)
print(x)
np.mean(x)

[0.88091001 0.32527576 0.03611875 0.30138425 0.18629996 0.44087851
 0.6669846  0.01111527 0.50706116 0.61499079 0.2250183  0.74967585
 0.97775722 0.47222135 0.06759456 0.19556098 0.68317814 0.78046099
 0.28893208 0.37192973 0.38971154 0.95725593 0.18110264 0.6545859
 0.75314845 0.1658894  0.117011   0.54826432 0.00189103 0.55405463]


0.43687543688494124

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [30]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [40]:
x=np.random.randint(1,25,(5,5))
np.pad(x, pad_width=1, mode='constant', constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 24, 19, 15, 19,  8,  0],
       [ 0,  3,  4, 20, 19, 23,  0],
       [ 0, 24, 12, 12, 11,  6,  0],
       [ 0,  7,  5, 18, 18, 22,  0],
       [ 0,  1,  7, 14, 24, 13,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [41]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [47]:
Z = np.diag(1+np.arange(4),k=1)
Z

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [57]:
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 5
Z

array([[0, 5, 0, 5, 0, 5, 0, 5],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 5, 0, 5, 0, 5, 0, 5],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 5, 0, 5, 0, 5, 0, 5],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 5, 0, 5, 0, 5, 0, 5],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [68]:
print(np.unravel_index(100,(6,7,8)))

(0, 0)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [15]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
X=np.random.random((5,5))
X_min,X_max=X.min(),X.max()
X=(X-X_min)/(X_max-X_min)
X

array([[0.35252445, 0.81643609, 0.17305892, 0.74944777, 0.43196907],
       [0.90818384, 0.56961027, 0.94711586, 0.17942955, 0.48566033],
       [0.17314939, 0.15162705, 0.28805613, 0.42329717, 0.        ],
       [0.80016551, 0.82688958, 0.84425436, 0.57300828, 0.84258048],
       [1.        , 0.9148345 , 0.72194598, 0.41374519, 0.37362921]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [34]:
x=np.random.randint(1,10,(5,3))
print(x)
y=np.random.randint(1,10,(3,2))
print(y)
print(x@y)

[[7 5 1]
 [4 7 2]
 [7 9 8]
 [5 2 5]
 [4 6 6]]
[[1 1]
 [7 4]
 [5 3]]
[[ 47  30]
 [ 63  38]
 [110  67]
 [ 44  28]
 [ 76  46]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [42]:
x=np.arange(15)
x[(3<x)&(x<=8)]*=-1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [43]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [56]:
Z=np.random.randint(1,10,3)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[5 2 4]
[3125    4  256]
[16  2  8]
[False False False]
[0.+5.j 0.+2.j 0.+4.j]
[5. 2. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [57]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

c:\users\валерия\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\валерия\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [62]:
#uniform -  нормальний розподіл
#copysign  - копирует знак с 1 в 2
#abs  - модуль

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 9.  3. -6.  5. 10.  4.  2. 10.  1.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [70]:
x=np.random.randint(1,25,(5,3))
print('x=',x)
y=np.random.randint(1,25,(2,3))
print('y=',y)
np.intersect1d(x,y)

x= [[ 2 12  7]
 [ 4 24  6]
 [24  4  9]
 [ 9 21  7]
 [10 16  7]]
y= [[19  6 16]
 [ 5 15 12]]


array([ 6, 12, 16])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [71]:
np.sqrt(-1) == np.emath.sqrt(-1)

c:\users\валерия\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [74]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2018-05-20 2018-05-21 2018-05-22


 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [82]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [88]:
x=np.zeros((5,5))
x+=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)